name: Christopher Adams
title: christopheradams.io
description: >
  Articles and Photographs by Christopher Adams.
email: email@christopheradams.io
default_img: /assets/img/christopher_pxlpeep_med.png

url: https://christopheradams.io

source_url: "https://github.com/christopheradams/christopheradams.io/blob/master/"

social:
  - name: twitter
    url: https://twitter.com/christopheradam
  - name: instagram
    url: https://www.instagram.com/christopherleeadams/
  - name: github
    url: https://github.com/christopheradams
  - name: flickr
    url: https://www.flickr.com/photos/christopheradams/

# Author settings
author:
  name: Christopher Adams
  uri: https://christopheradams.io

# Pagination settings
collections:
  category:
    output: true
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:year/:month/:title/
      author: christopheradams
  - scope:
      path: ""
      type: category
    values:
      layout: category
      permalink: /:title/
      author: Christopher Adams
paginate: 9
paginate_path: "/page/:num/"

# Image settings
responsive_image:
  template: _includes/srcset-resized-fallback.html
  base_path: assets/media
  output_path_format: assets/resized/%{width}/%{dirname}/%{basename}
  sizes:
    - width: 480
    - width: 800
    - width: 1080
  extra_images:
    - assets/media/*.{jpeg,jpg}

license: "CC-by"
license_url: https://creativecommons.org/licenses/by/4.0/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - CNAME
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - screenshot.png
  - webpack.dev.js
  - webpack.prod.js
  - webpack.common.js
