title: christopheradams.io
description: "Christopher Adams"
author: "Christopher Adams"
exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock, CNAME]
gems: ["jekyll-paginate", "jekyll-feed"]

url: https://christopheradams.io

permalink: /:categories/:year/:month/:title/
paginate_path: "/blog/page:num/"
paginate: 10

email: email@christopheradams.io
github_username: christopheradams
twitter_username: christopheradam

source_url: "https://github.com/christopheradams/christopheradams.github.io/blob/master/"

license: "CC-by"
license_url: https://creativecommons.org/licenses/by/4.0/
