title: christopheradams.github.io
description: "Christopher Adams"
author: "Christopher Adams"
exclude: [README.md, LICENSE.md, Gemfile, Gemfile.lock]
gems: ["jekyll-paginate"]

permalink: /:categories/:year/:month/:title/
paginate_path: "/blog/page:num/"
paginate: 10

github_username: christopheradams

license: "CC-by"
license_url: https://creativecommons.org/licenses/by/4.0/
