title: christopheradams.io
description: "Christopher Adams"
author: "Christopher Adams"

url: https://christopheradams.io

permalink: /:categories/:year/:month/:title/
paginate_path: "/blog/page:num/"
paginate: 10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:categories/:year/:month/:title/

email: email@christopheradams.io
github_username: christopheradams
twitter_username: christopheradam
flickr_username: christopheradams

source_url: "https://github.com/christopheradams/christopheradams.io/blob/master/"

license: "CC-by"
license_url: https://creativecommons.org/licenses/by/4.0/

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - LICENSE
  - README.md
  - package-lock.json
  - package.json
  - webpack.config.js
